import 'package:littletech/src/features/game/constants/game_data.dart';

class WeeklyBossManager {
  static final List<BossEncounterDef> _bosses = [
    BossEncounterDef(
      id: 'weekly_boss_1',
      name: 'The Cache Titan',
      lore: 'A massive entity born from corrupted cache lines, hoarding data and refusing to release it.',
      hp: 7, points: 700, armor: 16, challengeRating: 6,
      visualType: 1, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_1',
      abilities: ['Cache Lock', 'Data Hoarding', 'Stale Read'],
      diagnosis: {
        'symptoms': 'System repeatedly reads outdated data despite fresh writes. Performance degrades under load.',
        'options': ['Cache coherency failure across cores', 'RAM module failing', 'Disk read/write bottleneck'],
        'correct': 0,
        'flavor': 'You trace the stale reads to the L2 cache! The Titan\'s grip weakens!',
        'failFlavor': 'Wrong! The Titan locks more cache lines.',
      },
      strategies: [
        {'name': 'Cache flush', 'success': 70, 'damage': 2, 'flavor': 'Flushed! Stale data purged!', 'failFlavor': 'The Titan resists the flush command.'},
        {'name': 'Write-through bypass', 'success': 55, 'damage': 3, 'flavor': 'Writes bypass the corrupted cache!', 'failFlavor': 'The Titan intercepts the bypass.'},
        {'name': 'Cache line invalidation', 'success': 50, 'damage': 3, 'flavor': 'Invalidated! Lines cleared!', 'failFlavor': 'The Titan revalidates instantly.'},
        {'name': 'Full cache rebuild', 'success': 40, 'damage': 4, 'flavor': 'Cache rebuilt from clean source!', 'failFlavor': 'The Titan corrupts the rebuild.'},
        {'name': 'Hardware cache reset', 'success': 35, 'damage': 5, 'flavor': 'Hardware reset destroys the Titan\'s hold!', 'failFlavor': 'The Titan survives the reset.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_2',
      name: 'The Memory Devourer',
      lore: 'A ravenous beast that consumes RAM byte by byte, leaving nothing but crash dumps in its wake.',
      hp: 7, points: 750, armor: 16, challengeRating: 6,
      visualType: 2, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_2',
      abilities: ['Memory Leak', 'Heap Overflow', 'Swap Storm'],
      diagnosis: {
        'symptoms': 'Available memory drops steadily. Apps crash with out-of-memory errors. Swap usage spikes.',
        'options': ['Memory leak in a running process', 'Faulty RAM stick', 'Page file corruption'],
        'correct': 0,
        'flavor': 'You find the leak source! The Devourer\'s feast is interrupted!',
        'failFlavor': 'Wrong! The Devourer consumes more memory.',
      },
      strategies: [
        {'name': 'Process memory profiling', 'success': 70, 'damage': 2, 'flavor': 'Profiling reveals the leak!', 'failFlavor': 'The Devourer hides its allocations.'},
        {'name': 'Garbage collection force', 'success': 55, 'damage': 3, 'flavor': 'GC reclaims abandoned objects!', 'failFlavor': 'The Devourer prevents collection.'},
        {'name': 'Memory pool isolation', 'success': 50, 'damage': 3, 'flavor': 'Isolated! The leak is contained!', 'failFlavor': 'The Devourer spreads to new pools.'},
        {'name': 'OOM killer activation', 'success': 45, 'damage': 4, 'flavor': 'The killer terminates the leaking process!', 'failFlavor': 'The Devourer protects its host process.'},
        {'name': 'Full memory realloc', 'success': 35, 'damage': 5, 'flavor': 'Complete realloc starves the Devourer!', 'failFlavor': 'The Devourer feeds on the realloc itself.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_3',
      name: 'The Kernel Wraith',
      lore: 'A spectral force that haunts the kernel space, corrupting system calls and destabilizing the OS from within.',
      hp: 8, points: 800, armor: 17, challengeRating: 7,
      visualType: 3, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_3',
      abilities: ['Kernel Panic', 'System Call Corruption', 'Ring Zero Invasion'],
      diagnosis: {
        'symptoms': 'Random kernel panics. System calls return garbage. Blue screens with kernel-mode errors.',
        'options': ['Faulty kernel module or driver', 'Hard drive failure', 'Power supply instability'],
        'correct': 0,
        'flavor': 'You isolate the corrupt module! The Wraith\'s form flickers!',
        'failFlavor': 'Wrong! The Wraith deepens its corruption.',
      },
      strategies: [
        {'name': 'Safe mode boot', 'success': 70, 'damage': 2, 'flavor': 'Safe mode bypasses the Wraith!', 'failFlavor': 'The Wraith follows into safe mode.'},
        {'name': 'Driver rollback', 'success': 55, 'damage': 3, 'flavor': 'Rolled back to clean driver!', 'failFlavor': 'The Wraith corrupted the backup.'},
        {'name': 'Kernel debug session', 'success': 50, 'damage': 3, 'flavor': 'Debug traces reveal the Wraith!', 'failFlavor': 'The Wraith obscures the traces.'},
        {'name': 'System file restore', 'success': 45, 'damage': 4, 'flavor': 'Clean kernel files restored!', 'failFlavor': 'The Wraith infects the restore.'},
        {'name': 'Full kernel rebuild', 'success': 35, 'damage': 5, 'flavor': 'Fresh kernel banishes the Wraith!', 'failFlavor': 'The Wraith embeds in the build.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_4',
      name: 'The Feedback Phantom',
      lore: 'A shrieking specter that weaponizes audio feedback, deafening systems and shattering speaker cones.',
      hp: 7, points: 700, armor: 16, challengeRating: 6,
      visualType: 4, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_4',
      abilities: ['Feedback Loop', 'Waveform Distortion', 'Speaker Shatter'],
      diagnosis: {
        'symptoms': 'Loud screeching from speakers. Audio output distorted. Microphone picks up its own output.',
        'options': ['Audio feedback loop between mic and speakers', 'Corrupted audio codec', 'Damaged speaker hardware'],
        'correct': 0,
        'flavor': 'You break the feedback loop! The Phantom\'s scream falters!',
        'failFlavor': 'Wrong! The Phantom amplifies the feedback.',
      },
      strategies: [
        {'name': 'Mute microphone', 'success': 75, 'damage': 2, 'flavor': 'Mic muted! Loop broken!', 'failFlavor': 'The Phantom routes audio through another path.'},
        {'name': 'Noise cancellation', 'success': 55, 'damage': 3, 'flavor': 'Cancellation waveform neutralizes feedback!', 'failFlavor': 'The Phantom shifts frequency.'},
        {'name': 'Audio driver restart', 'success': 50, 'damage': 3, 'flavor': 'Driver reset clears the distortion!', 'failFlavor': 'The Phantom persists across resets.'},
        {'name': 'Hardware isolation', 'success': 45, 'damage': 4, 'flavor': 'Isolated audio device stops the loop!', 'failFlavor': 'The Phantom jumps to another device.'},
        {'name': 'Full audio stack rebuild', 'success': 35, 'damage': 5, 'flavor': 'Clean audio stack banishes the Phantom!', 'failFlavor': 'The Phantom haunts the new stack.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_5',
      name: 'The Input Overlord',
      lore: 'A tyrant that seizes control of all input devices, typing its own commands and moving cursors at will.',
      hp: 7, points: 750, armor: 16, challengeRating: 6,
      visualType: 5, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_5',
      abilities: ['Input Hijack', 'Keystroke Injection', 'Cursor Possession'],
      diagnosis: {
        'symptoms': 'Mouse moves on its own. Random keystrokes appear. Input devices become unresponsive to user.',
        'options': ['Input device driver hijack or malware', 'Loose USB connection', 'Electromagnetic interference'],
        'correct': 0,
        'flavor': 'You find the hijack source! The Overlord loses its grip!',
        'failFlavor': 'Wrong! The Overlord seizes more devices.',
      },
      strategies: [
        {'name': 'Device manager disable', 'success': 70, 'damage': 2, 'flavor': 'Disabled! Overlord loses control!', 'failFlavor': 'The Overlord re-enables the device.'},
        {'name': 'USB selective suspend', 'success': 55, 'damage': 3, 'flavor': 'Suspended! Input redirected to user!', 'failFlavor': 'The Overlord bypasses the suspend.'},
        {'name': 'Driver reinstall', 'success': 50, 'damage': 3, 'flavor': 'Clean driver installed!', 'failFlavor': 'The Overlord corrupts the installer.'},
        {'name': 'Input filter driver', 'success': 45, 'damage': 4, 'flavor': 'Filter blocks Overlord commands!', 'failFlavor': 'The Overlord bypasses the filter.'},
        {'name': 'Full HID stack reset', 'success': 35, 'damage': 5, 'flavor': 'HID reset destroys the Overlord!', 'failFlavor': 'The Overlord survives the reset.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_6',
      name: 'The Dependency Demon',
      lore: 'A cunning trickster that corrupts package dependencies, causing cascading failures across entire software stacks.',
      hp: 8, points: 850, armor: 18, challengeRating: 7,
      visualType: 6, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_6',
      abilities: ['Version Conflict', 'Dependency Hell', 'Package Corruption'],
      diagnosis: {
        'symptoms': 'Software fails to start with missing DLL errors. Package manager reports conflicts. Updates break other packages.',
        'options': ['Dependency version conflict or corruption', 'Disk space exhaustion', 'Network connectivity issue'],
        'correct': 0,
        'flavor': 'You resolve the version conflict! The Demon\'s web unravels!',
        'failFlavor': 'Wrong! The Demon creates more conflicts.',
      },
      strategies: [
        {'name': 'Clean reinstall', 'success': 65, 'damage': 2, 'flavor': 'Fresh install with correct deps!', 'failFlavor': 'The Demon corrupts the reinstall.'},
        {'name': 'Dependency tree audit', 'success': 55, 'damage': 3, 'flavor': 'Audit finds the broken link!', 'failFlavor': 'The Demon hides the broken deps.'},
        {'name': 'Version pinning', 'success': 50, 'damage': 3, 'flavor': 'Pinned versions stop conflicts!', 'failFlavor': 'The Demon forces version resolution.'},
        {'name': 'Virtual environment isolation', 'success': 45, 'damage': 4, 'flavor': 'Isolated env contains the Demon!', 'failFlavor': 'The Demon escapes the environment.'},
        {'name': 'Full dependency rebuild', 'success': 35, 'damage': 5, 'flavor': 'Complete rebuild banishes the Demon!', 'failFlavor': 'The Demon infects the rebuild.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_7',
      name: 'The Latency Leviathan',
      lore: 'A colossal sea beast dwelling in the depths of network stacks, dragging every packet through miles of virtual mud.',
      hp: 8, points: 900, armor: 18, challengeRating: 7,
      visualType: 7, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_7',
      abilities: ['Packet Delay', 'Buffer Bloat', 'Route Congestion'],
      diagnosis: {
        'symptoms': 'Extreme latency on all connections. Speed tests show normal bandwidth but ping times in seconds.',
        'options': ['Network buffer bloat or route congestion', 'DNS resolution failure', 'Firewall blocking packets'],
        'correct': 0,
        'flavor': 'You clear the congestion! The Leviathan surfaces!',
        'failFlavor': 'Wrong! The Leviathan deepens the lag.',
      },
      strategies: [
        {'name': 'QoS prioritization', 'success': 65, 'damage': 2, 'flavor': 'Priority queues clear the backlog!', 'failFlavor': 'The Leviathan floods the queues.'},
        {'name': 'Buffer tuning', 'success': 55, 'damage': 3, 'flavor': 'Smaller buffers reduce delay!', 'failFlavor': 'The Leviathan overflows the buffers.'},
        {'name': 'Route optimization', 'success': 50, 'damage': 3, 'flavor': 'Shorter route found!', 'failFlavor': 'The Leviathan blocks the new route.'},
        {'name': 'Traffic shaping', 'success': 45, 'damage': 4, 'flavor': 'Shaping controls the flood!', 'failFlavor': 'The Leviathan overwhelms the shaper.'},
        {'name': 'Full network stack reset', 'success': 35, 'damage': 5, 'flavor': 'Reset clears all congestion!', 'failFlavor': 'The Leviathan survives the reset.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_8',
      name: 'The Bit Rot Behemoth',
      lore: 'An ancient horror that slowly decays data on disk, turning valid files into unreadable garbage over time.',
      hp: 9, points: 950, armor: 19, challengeRating: 8,
      visualType: 8, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_8',
      abilities: ['Data Decay', 'Sector Corruption', 'File Entropy'],
      diagnosis: {
        'symptoms': 'Files become corrupted over time. Checksums fail.磁盘 surfaces show increasing bad sectors.',
        'options': ['Physical disk degradation or bit rot', 'File system corruption', 'Power surge damage'],
        'correct': 0,
        'flavor': 'You find the decaying sectors! The Behemoth weakens!',
        'failFlavor': 'Wrong! The Behemoth spreads the rot.',
      },
      strategies: [
        {'name': 'S.M.A.R.T. diagnostics', 'success': 65, 'damage': 2, 'flavor': 'Diagnostics reveal failing sectors!', 'failFlavor': 'The Behemoth masks the S.M.A.R.T. data.'},
        {'name': 'Sector reallocation', 'success': 55, 'damage': 3, 'flavor': 'Bad sectors reallocated!', 'failFlavor': 'The Behemoth corrupts new sectors.'},
        {'name': 'File system check', 'success': 50, 'damage': 3, 'flavor': 'fsck repairs the damage!', 'failFlavor': 'The Behemoth hides the corruption.'},
        {'name': 'Data migration', 'success': 45, 'damage': 4, 'flavor': 'Data moved to healthy disk!', 'failFlavor': 'The Behemoth follows the data.'},
        {'name': 'Full disk rebuild', 'success': 35, 'damage': 5, 'flavor': 'Fresh disk destroys the Behemoth!', 'failFlavor': 'The Behemoth embeds in the firmware.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_9',
      name: 'The Pixel Punisher',
      lore: 'A distorted entity that attacks display outputs, scrambling pixels and turning screens into walls of static.',
      hp: 8, points: 850, armor: 18, challengeRating: 7,
      visualType: 9, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_9',
      abilities: ['Pixel Corruption', 'Signal Scramble', 'Refresh Rate Attack'],
      diagnosis: {
        'symptoms': 'Display shows corrupted pixels. Random artifacts appear. Screen flickers or shows wrong colors.',
        'options': ['GPU driver corruption or signal issue', 'Monitor hardware failure', 'Cable connection problem'],
        'correct': 0,
        'flavor': 'You restore the signal! The Punisher\'s distortion fades!',
        'failFlavor': 'Wrong! The Punisher corrupts more pixels.',
      },
      strategies: [
        {'name': 'Driver reinstall', 'success': 65, 'damage': 2, 'flavor': 'Clean driver restores display!', 'failFlavor': 'The Punisher corrupts the install.'},
        {'name': 'Signal re-sync', 'success': 55, 'damage': 3, 'flavor': 'Sync restored! Clear image!', 'failFlavor': 'The Punisher desynchronizes again.'},
        {'name': 'GPU memory test', 'success': 50, 'damage': 3, 'flavor': 'VRAM errors found and corrected!', 'failFlavor': 'The Punisher hides the errors.'},
        {'name': 'Display pipeline reset', 'success': 45, 'damage': 4, 'flavor': 'Pipeline reset clears artifacts!', 'failFlavor': 'The Punisher reasserts control.'},
        {'name': 'Full graphics stack rebuild', 'success': 35, 'damage': 5, 'flavor': 'Fresh stack banishes the Punisher!', 'failFlavor': 'The Punisher survives in firmware.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_10',
      name: 'The Battery Banshee',
      lore: 'A wailing phantom that drains battery life at impossible rates, leaving devices dead in minutes.',
      hp: 8, points: 800, armor: 17, challengeRating: 7,
      visualType: 10, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_10',
      abilities: ['Power Drain', 'Thermal Spike', 'Sleep Prevention'],
      diagnosis: {
        'symptoms': 'Battery drains in minutes. Device runs hot even idle. Sleep mode fails to activate.',
        'options': ['Background process drain or thermal issue', 'Faulty battery cell', 'Charging circuit failure'],
        'correct': 0,
        'flavor': 'You find the drain source! The Banshee\'s wail weakens!',
        'failFlavor': 'Wrong! The Banshee drains more power.',
      },
      strategies: [
        {'name': 'Process audit', 'success': 70, 'damage': 2, 'flavor': 'Killing rogue process restores battery!', 'failFlavor': 'The Banshee hides the process.'},
        {'name': 'Power profile reset', 'success': 55, 'damage': 3, 'flavor': 'Balanced profile reduces drain!', 'failFlavor': 'The Banshee overrides the profile.'},
        {'name': 'Thermal throttling', 'success': 50, 'damage': 3, 'flavor': 'Throttling cools the device!', 'failFlavor': 'The Banshee bypasses throttling.'},
        {'name': 'Driver power management', 'success': 45, 'damage': 4, 'flavor': 'Power management restored!', 'failFlavor': 'The Banshee corrupts the driver.'},
        {'name': 'Full power stack rebuild', 'success': 35, 'damage': 5, 'flavor': 'Fresh power stack banishes Banshee!', 'failFlavor': 'The Banshee survives the rebuild.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_11',
      name: 'The Lag Dragon',
      lore: 'A fire-breathing beast that scorches frame rates, leaving nothing but stuttering slideshows in its path.',
      hp: 9, points: 1000, armor: 19, challengeRating: 8,
      visualType: 11, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_11',
      abilities: ['Frame Drop', 'Input Lag Burst', 'GPU Overload'],
      diagnosis: {
        'symptoms': 'Frame rates plummet during gameplay. Input feels delayed. GPU usage spikes to 100%.',
        'options': ['GPU bottleneck or thermal throttling', 'Network latency issue', 'Hard drive bottleneck'],
        'correct': 0,
        'flavor': 'You clear the GPU bottleneck! The Dragon\'s flames dim!',
        'failFlavor': 'Wrong! The Dragon increases the heat.',
      },
      strategies: [
        {'name': 'Graphics settings reduction', 'success': 65, 'damage': 2, 'flavor': 'Lower settings boost frames!', 'failFlavor': 'The Dragon adapts to new settings.'},
        {'name': 'Driver optimization', 'success': 55, 'damage': 3, 'flavor': 'Optimized driver improves performance!', 'failFlavor': 'The Dragon corrupts the optimization.'},
        {'name': 'Background process kill', 'success': 50, 'damage': 3, 'flavor': 'Freed GPU resources!', 'failFlavor': 'The Dragon spawns new processes.'},
        {'name': 'GPU overclock', 'success': 45, 'damage': 4, 'flavor': 'Extra power burns through the Dragon!', 'failFlavor': 'The Dragon absorbs the extra power.'},
        {'name': 'Full graphics pipeline reset', 'success': 35, 'damage': 5, 'flavor': 'Pipeline reset destroys the Dragon!', 'failFlavor': 'The Dragon survives the reset.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_12',
      name: 'The Signal Specter',
      lore: 'A ghostly presence that haunts wireless networks, causing devices to lose connection at the worst moments.',
      hp: 8, points: 900, armor: 18, challengeRating: 7,
      visualType: 12, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_12',
      abilities: ['Signal Jam', 'Interference Burst', 'Drop Disconnect'],
      diagnosis: {
        'symptoms': 'Wi-Fi drops intermittently. Signal strength fluctuates wildly. Devices reconnect constantly.',
        'options': ['Wireless interference or channel congestion', 'Router hardware failure', 'ISP outage'],
        'correct': 0,
        'flavor': 'You clear the interference! The Specter\'s signal fades!',
        'failFlavor': 'Wrong! The Specter jams more channels.',
      },
      strategies: [
        {'name': 'Channel scan and switch', 'success': 65, 'damage': 2, 'flavor': 'Clean channel found!', 'failFlavor': 'The Specter follows to the new channel.'},
        {'name': 'Signal boost', 'success': 55, 'damage': 3, 'flavor': 'Stronger signal overpowers interference!', 'failFlavor': 'The Specter amplifies the jamming.'},
        {'name': 'Band steering', 'success': 50, 'damage': 3, 'flavor': '5GHz band avoids the Specter!', 'failFlavor': 'The Specter jams both bands.'},
        {'name': 'Antenna repositioning', 'success': 45, 'damage': 4, 'flavor': 'Better position clears the signal!', 'failFlavor': 'The Specter repositions the interference.'},
        {'name': 'Full wireless stack reset', 'success': 35, 'damage': 5, 'flavor': 'Reset banishes the Specter!', 'failFlavor': 'The Specter survives the reset.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_13',
      name: 'The Exploit Emperor',
      lore: 'A tyrannical overlord that discovers and weaponizes zero-day vulnerabilities, conquering systems before defenders even know they exist.',
      hp: 10, points: 1100, armor: 20, challengeRating: 8,
      visualType: 13, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_13',
      abilities: ['Zero-Day Strike', 'Privilege Escalation', 'Backdoor Creation'],
      diagnosis: {
        'symptoms': 'Unauthorized admin access detected. Unknown processes running with system privileges. Security logs show anomalies.',
        'options': ['Zero-day exploit with privilege escalation', 'Weak password attack', 'Physical security breach'],
        'correct': 0,
        'flavor': 'You trace the exploit chain! The Emperor\'s throne cracks!',
        'failFlavor': 'Wrong! The Emperor escalates further.',
      },
      strategies: [
        {'name': 'Patch deployment', 'success': 60, 'damage': 2, 'flavor': 'Patch closes the vulnerability!', 'failFlavor': 'The Emperor exploits a different vector.'},
        {'name': 'Privilege audit', 'success': 55, 'damage': 3, 'flavor': 'Revoked excess privileges!', 'failFlavor': 'The Emperor re-escalates.'},
        {'name': 'Process termination', 'success': 50, 'damage': 3, 'flavor': 'Killed the malicious process!', 'failFlavor': 'The Emperor spawns a new process.'},
        {'name': 'Backdoor detection', 'success': 45, 'damage': 4, 'flavor': 'Found and closed the backdoor!', 'failFlavor': 'The Emperor creates another backdoor.'},
        {'name': 'Full system lockdown', 'success': 35, 'damage': 5, 'flavor': 'Lockdown traps the Emperor!', 'failFlavor': 'The Emperor overrides the lockdown.'},
      ],
    ),
    BossEncounterDef(
      id: 'weekly_boss_14',
      name: 'The Packet Storm',
      lore: 'A swirling vortex of corrupted packets that overwhelms network infrastructure, drowning all communication in noise.',
      hp: 9, points: 1000, armor: 19, challengeRating: 8,
      visualType: 14, difficulty: DifficultyLevel.hard,
      bossKey: 'weekly_boss_14',
      abilities: ['Packet Flood', 'DNS Amplification', 'SYN Attack'],
      diagnosis: {
        'symptoms': 'Network completely saturated. All ports flooded with traffic. Legitimate connections time out.',
        'options': ['DDoS attack or packet flood', 'Network loop causing broadcast storm', 'Misconfigured load balancer'],
        'correct': 0,
        'flavor': 'You identify the flood source! The Storm weakens!',
        'failFlavor': 'Wrong! The Storm intensifies.',
      },
      strategies: [
        {'name': 'Rate limiting', 'success': 65, 'damage': 2, 'flavor': 'Rate limits control the flood!', 'failFlavor': 'The Storm overwhelms the limits.'},
        {'name': 'Firewall rules', 'success': 55, 'damage': 3, 'flavor': 'Rules block malicious packets!', 'failFlavor': 'The Storm finds allowed ports.'},
        {'name': 'Traffic analysis', 'success': 50, 'damage': 3, 'flavor': 'Analysis identifies attack pattern!', 'failFlavor': 'The Storm changes its pattern.'},
        {'name': 'BGP blackhole routing', 'success': 45, 'damage': 4, 'flavor': 'Blackhole drops attack traffic!', 'failFlavor': 'The Storm redirects through peers.'},
        {'name': 'Full network stack reset', 'success': 35, 'damage': 5, 'flavor': 'Reset clears the Storm!', 'failFlavor': 'The Storm rebuilds from backup.'},
      ],
    ),
  ];

  static List<BossEncounterDef> get all => _bosses;

  static BossEncounterDef getCurrent() {
    final now = DateTime.now();
    final daysSinceEpoch = now.millisecondsSinceEpoch ~/ Duration.millisecondsPerDay;
    final weekNumber = daysSinceEpoch ~/ 7;
    final index = weekNumber % _bosses.length;
    return _bosses[index];
  }
}
